version: '3'
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    volumes:
      - .:/usr/share/nginx/html/swagger
    environment:
      API_URL: ./swagger/main.swagger.json
    ports:
      - '8080:8080'